### PR TITLE
Set runtime dir permission to 770

### PR DESCRIPTION
**Pull request by lkolacek**
Increase group permissions for runtime directory so it can read/write/execute

CLOUDBLD-8995

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough

### CODE REVIEW

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

CI failures are unrelated

**Comment by ben-alkov** [comment]
> CI failures are unrelated

ansible-lint is complaining about [fqcn-builtins](https://ansible-lint.readthedocs.io/en/latest/default_rules/#fqcn-builtins) (I don't actually understand what that means...)

**Review by mkosiarc — APPROVED** [review]

**Comment by MartinBasti** [comment]
but still would be nice to address linter issues in separate PR

**Comment by ben-alkov** [comment]
> but still would be nice to address linter issues in separate PR

Agreed, I see now that those weren't introduced in this PR

**Comment by qixiang** [comment]
The [fqcn-builtins](https://ansible-lint.readthedocs.io/en/latest/default_rules/#fqcn-builtins) is loaded by default since ansible-lint 6.0.0 (released 3 days ago).
```
[v6.0.0]
Major Changes
...
* Made fqcn-builtins rule implicit (https://github.com/ansible-community/ansible-lint/pull/1908) @ssbarnea
```
We can merge https://github.com/containerbuildsystem/ansible-role-osbs-remote-hosts/pull/14 first and rebase this one.

**Pull request merged**
